version: '3.8'

services:
  api:
    build:
      context: ..  # <--- Apunta a la raíz del código Go
      dockerfile: deployment/Dockerfile
      target: prod
    container_name: golang_api
    restart: on-failure
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - SERVER_ADDRESS=${SERVER_ADDRESS:-:8080}
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSLMODE=${DB_SSLMODE:-disable}
      - REDIS_HOST=redis_cache
      - REDIS_PORT=6379
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - postgres
      - redis
    networks:
      - api_network

  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - api_network

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - api_network

volumes:
  postgres_data:
  redis_data:

networks:
  api_network:
    driver: bridge
